### PR TITLE
134 test coverage

### LINKED ISSUE #134: Increase test coverage
Multiple methods of classes in the util and audio packages feature Exception try/catch blocks. None of these are covered in our tests. We should also test these parts of our code by entering faulty data.

If testing is not possible, please explain why in the comments.

Unit Tests
- [x] Logger
- [x] SoundTrackPlayer
- [x] SoundEffectPlayer
- [x] Trackparser (checkformat/parsetrackpart null)
- [ ] Savegame (@MathiasMeuleman)

E2E
- [ ] HighScoreScene (@mpsijm)

### PR DESCRIPTION
**Pull request by thervh70**
Will close #134 

This PR contains several test additions and also code deletions.
It aims at increasing the test coverage if it is feasible.
The other part of this issue will be done in #174 and #167.

When reviewing, please check whether I have been right in deleting certain methods. I have done what my IDE told me was unused and uncovered by tests.

< testing

### CODE REVIEW

File: src/main/java/nl/tudelft/ti2206/group9/level/State.java [hunk 1]
```diff
@@ -65,7 +66,7 @@ public static void resetAll() {
         setCoins(0);
         highscore = 0;
         previousDistance = 0;
-        skin = Skin.getNoob();
+        skin = Skin.loadSkinsToList().get(0);
```
Comment (MathiasMeuleman) [inline src/main/java/nl/tudelft/ti2206/group9/level/State.java]: Is this a smart thing to do? This way you hardcode the position of the Noobskin in the List.

<review

File: src/test/java/nl/tudelft/ti2206/group9/gui/EndToEndTest.java [hunk 2]
```diff
@@ -203,15 +205,17 @@ private void goThroughShop() {
...
+        assertEquals(State.getSkin(), skinList.get(0));
         shopBuyEquipSkin(SHOP_SKIN_CAPTAIN);
-        assertEquals(State.getSkin(), Skin.getNoob());
+        assertEquals(State.getSkin(), skinList.get(0));
         shopBuyEquipSkin(SHOP_SKIN_CAPTAIN);
-        assertEquals(State.getSkin(), Skin.getAndy());
+        assertEquals(State.getSkin(), skinList.get(1));
         shopBuyEquipSkin(SHOP_SKIN_IRONMAN);
-        assertEquals(State.getSkin(), Skin.getNoob());
+        assertEquals(State.getSkin(), skinList.get(0));
```
Comment (MathiasMeuleman) [inline src/test/java/nl/tudelft/ti2206/group9/gui/EndToEndTest.java]: Here also, don't harcode the position of the skins in the list

<review

**Comment by MathiasMeuleman** [comment]
Please review my comments about harcoded skins.
Also, testGoodWeather in HighscoreClientTest hangs. I heared this has been a problem before, so please check what the cause of this could be (and fix!)

<review

File: src/main/java/nl/tudelft/ti2206/group9/level/State.java (hunk 1 above)
Comment (thervh70) [inline src/main/java/nl/tudelft/ti2206/group9/level/State.java]: Yes, it is true that i hardcoded this. But isn't it logical the first item on the list is the noobskin? I wanted to get rid of all the getters and this is the best way I imagined.

**Comment by mpsijm** [comment]
@MathiasMeuleman as long as the test doesn't hang in Travis, it's fine for now. I'll fix the server tests in #174b :) 

<review,testing

File: src/main/java/nl/tudelft/ti2206/group9/level/State.java (hunk 1 above)
Comment (mpsijm) [inline src/main/java/nl/tudelft/ti2206/group9/level/State.java]: Then at least make a constant out of it, something like `NOOB_SKIN_POS`. Even though it's not a "magic number", I agree it's still hardcoding a list position.
This has also been done with the position of the Player in Track's List<Entity>.

<review,logic

File: src/test/java/nl/tudelft/ti2206/group9/gui/EndToEndTest.java [hunk 3]
```diff
@@ -152,19 +150,23 @@ public void test() throws IOException { //NOPMD - assert is done in subs.
...
+    private void outputEventLog() {
+        try {
+            ShaftEscape.LOGGER.writeToFile();
+            final String log = new String(Files.readAllBytes(
+                    Paths.get(Logger.OUTFILE)), StandardCharsets.UTF_8);
+            System.out.println("\n== EVENT_LOG ==");     //NOPMD - Intended use of
+            System.out.println(log);                     //NOPMD - System.out.print
+            System.out.println("== END_EVENT_LOG ==\n"); //NOPMD - for Travis log
+        } catch (IOException e) {
+            fail();
```
Comment (mpsijm) [inline src/test/java/nl/tudelft/ti2206/group9/gui/EndToEndTest.java]: Should the E2E really fail when the log cannot be printed to the console? Maybe it's better just to print "log could not be printed" or something like that, including the Exception message.

<review, testing, logic

File: src/test/java/nl/tudelft/ti2206/group9/gui/EndToEndTest.java (hunk 2 above)
Comment (mpsijm) [inline src/test/java/nl/tudelft/ti2206/group9/gui/EndToEndTest.java]: Well, the buttons that get clicked in the interleaved lines also have hardcoded numbers 0 and 1. The E2E doesn't have to care which skins are actually bought, as long as it notices "when I click on button no. 1, skin no. 1 is bought. When I click again, skin no. 1 is equipped". Positions 0 and 1 (maybe even 2) can be used for this purpose.

<review, testing, logic

File: src/test/java/nl/tudelft/ti2206/group9/util/LoggerTest.java [hunk 4]
```diff
@@ -32,23 +32,27 @@ public void setUp() {
...
+            assertEquals(testUpdateString, log);
+
+            // append = false, thus a new file should be created
+            logger.update(null, testUpdate);
+            logger.writeToFile(false);
+            log = new String(Files.readAllBytes(Paths.get(TESTLOG)),
+                    StandardCharsets.UTF_8).substring(Logger.FORMAT.length() - 1);
+            assertEquals(testUpdateString, log);
+        } catch (IOException e) {
+            fail();
```
Comment (mpsijm) [inline src/test/java/nl/tudelft/ti2206/group9/util/LoggerTest.java]: When the test fails at this point, is it easy to see why? Because if it's not, you should add a message to the method like `fail("IOException in test <...>");

<review, logic

File: src/test/java/nl/tudelft/ti2206/group9/gui/EndToEndTest.java (hunk 3 above)
Comment (thervh70) [inline src/test/java/nl/tudelft/ti2206/group9/gui/EndToEndTest.java]: No I do not agree. It is not acceptable if this exception makes it to the test. It should be caught earlier in a method. Any exception that can be seen by a test (which acts as the user in this case) is wrong and should result in a failure.

The whole point of catching exceptions is that the user is not able to see that something is going wrong. If he does see something, that means some components are failing

< review, logic

File: src/test/java/nl/tudelft/ti2206/group9/util/LoggerTest.java (hunk 4 above)
Comment (thervh70) [inline src/test/java/nl/tudelft/ti2206/group9/util/LoggerTest.java]: I agree, i will add a string to all `fail` methods in the test package.

It will look like this. The stacktrace will show the test and the message of the fail shows the exception thrown.
```
java.lang.AssertionError: IOException was thrown
	at nl.tudelft.ti2206.group9.util.LoggerTest.testWriteToFile(LoggerTest.java:48)
```

**Comment by MKerkhof** [comment]
Looks good! No hanging here, every tests seems to run fine! 

Code looks good and no SAT warnings left! If someone else can review your latest commits too I think this is ready to be merged!

<review

**Comment by mpsijm** [comment]
Thanks for processing my feedback, will merge! :)

<review
